<<<<<<< HEAD
version: '3.7'
services: 
  nginx: nginx:stable-alpine
  container_name: nginx
  restart: always
  ports: 
    - 8888:80
  volumes: 
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on: 
    - php
    - mysql
  networks: 
    - laravel
=======
version: "3.7"
  services: 
    nginx: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports: 
      - 8888:80
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel
>>>>>>> 7936cbfdd4d91cd6595a32ce0115172c7c19afac

mysql:
  image: mysql:5.7
  container_name: mysql
  restart: always
  environment: 
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: admin.root
  ports: 
    - 33069:3306
  volumes: 
    - ./mysql:/var/lib/mysql
  networks: 
    - laravel

php:
  build: 
    context: .
    dockerfile: Dockerfile
  container_name: php
  volumes: 
    - ./src:/var/www/html
  ports: 
    - 9000:80
  networks: 
    - laravel
    
networks: 
  laravel:
